import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeRegistry from "./ThemeRegistry";
import Navbar from "@/components/navbar";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CRUD app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <ThemeRegistry options={{key: 'joy'}} >
            <Navbar />
            <main className="max-w-4xl mx-auto p-5 sm:p-10 " >{children}</main>
            <Toaster />
        </ThemeRegistry>
      </body>
    </html>
  );
}
